CREATE TABLE IF NOT EXISTS rooms
(
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS students
(
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(100) NOT NULL,
    room INTEGER NOT NULL,
    sex CHARACTER(1) NOT NULL,
    birthday TIMESTAMP NOT NULL,
    FOREIGN KEY (room) REFERENCES rooms (Id) ON DELETE CASCADE
);
